# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='makeeya.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Business_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
