# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='request',
        ),
    ]
