# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Business_name',
            new_name='business_address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='logo',
            new_name='business_logo',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='address',
            new_name='business_name',
        ),
    ]
