# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0002_auto_20190613_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Identification_number',
            new_name='business_identification_number',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='phone_number',
            new_name='business_phone_number',
        ),
    ]
