# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0003_auto_20190613_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Business_address',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
