# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeeya', '0004_request_business_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='profile',
        ),
    ]
